apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  startingCSV: rhcl-operator.v1.1.0
  config:
    env:
      - name: ISTIO_GATEWAY_CONTROLLER_NAMES
        value: openshift.io/gateway-controller/v1
