apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    distributedworkload: "true"
    v3: "true"
resources:
  # Add jobset operator resources here
  # Example: subscription.yaml, operatorgroup.yaml
