apiVersion: kueue.openshift.io/v1
kind: Kueue
metadata:
  name: cluster
spec:
  managementState: Managed
  config:
    integrations:
      frameworks:
        - Deployment
        - Pod  
        - PyTorchJob
        - RayCluster
        - RayJob
        - StatefulSet
